name: Demo Workflow

on:
  push:
    branches: [ "develop" ]

jobs:
  test-echo:
    runs-on: ubuntu-latest
    name: Test echo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: echo
        run: echo 'Hello world'
        
  list-files:
    runs-on: ubuntu-latest
    name: List Files
    needs: test-echo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files in repo
        run: ls -R

